In [35]:
import pandas as pd 
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
import scipy as stats
import datetime as dt

In [36]:
# loading Data
customer = pd.read_csv("C:\\Users\\Asus\\Downloads\\customer_shopping_behavior.csv")

In [43]:
customer.head()

,Customer_ID,Age,Gender,Item_Purchased,Category,Purchase_Amount_(USD),Location,Size,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Payment_Method,Frequency_of_Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [44]:
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer_ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item_Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase_Amount_(USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review_Rating           3863 non-null   float64
 11  Subscription_Status     3900 non-null   object
 12  Shipping_Type           3900 non-null   object
 13  Discount_Applied        3900 non-null   object
 14  Promo_Code_Used         3900 non-null   object
 15  Previous_Purchases      3900 non-null   int64
 16  Payment_Method          3900 non-null   object
 17  Frequency_of_Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [45]:
customer.describe()

,Customer_ID,Age,Purchase_Amount_(USD),Review_Rating,Previous_Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [48]:
customer.describe(include="object").T

                       count unique             top  freq
Gender                  3900      2            Male  2652
Item_Purchased          3900     25          Blouse   171
Category                3900      4        Clothing  1737
Location                3900     50         Montana    96
Size                    3900      4               M  1755
Color                   3900     25           Olive   177
Season                  3900      4          Spring   999
Subscription_Status     3900      2              No  2847
Shipping_Type           3900      6   Free Shipping   675
Discount_Applied        3900      2              No  2223
Promo_Code_Used         3900      2              No  2223
Payment_Method          3900      6          PayPal   677
Frequency_of_Purchases  3900      7  Every 3 Months   584

In [47]:
customer.isna().sum()

Customer_ID                0
Age                        0
Gender                     0
Item_Purchased             0
Category                   0
Purchase_Amount_(USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review_Rating             37
Subscription_Status        0
Shipping_Type              0
Discount_Applied           0
Promo_Code_Used            0
Previous_Purchases         0
Payment_Method             0
Frequency_of_Purchases     0
dtype: int64

In [ ]:
# Handling missing value

In [ ]:
"""I use group-wise median imputation. I group the data by Category, calculate the median 
Review_Rating within each category, and use that category-specific median to fill missing values."""

In [52]:
#customer["Review_Rating"] = customer.groupby("Category")["Review_Rating"].transform(lambda x: x.fillna(median()))
median_rating=customer.groupby("Category").Review_Rating.mean()
customer["Review_Rating"] = customer["Review_Rating"].fillna(
    customer["Category"].map(median_rating)
)

In [54]:
# Removing Extra space in Columns
customer.columns=customer.columns.str.replace(" ","_")
customer.columns = customer.columns.str.lower()
 customer.rename(columns={"purchase_amount_(usd)":"purchase_amount"	},inplace=True )

In [62]:
# creating a olumns ag _group 
labels =["Young_Adult" , "Adult" , "Middle_age" ,"Senior"]
customer["Age_group"] = pd.qcut(customer.age,q=4 ,labels=labels)

In [64]:
customer[["age","Age_group"]]

      age    Age_group
0      55   Middle_age
1      19  Young_Adult
2      50   Middle_age
3      21  Young_Adult
4      45   Middle_age
...   ...          ...
3895   40        Adult
3896   52   Middle_age
3897   46   Middle_age
3898   44        Adult
3899   52   Middle_age

[3900 rows x 2 columns]

In [65]:
customer.frequency_of_purchases.value_counts()

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [66]:
# create columns purchase_frequency_days

frequency_mapping = {
    "Fortnightly":14,
    "Annually":365,
    "Weekly":7,
    "Bi-Weekly":14,
    "Monthly":30,
    "Quarterly":90,
    "Every 3 Months":90
}
customer["purchase_frequency_days"] = customer["frequency_of_purchases"].map(frequency_mapping)

In [67]:
customer

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,Age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle_age,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young_Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle_age,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young_Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle_age,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly,Adult,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly,Middle_age,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly,Middle_age,90
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly,Adult,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly,Middle_age,90

In [69]:
customer[["frequency_of_purchases","purchase_frequency_days"]]

     frequency_of_purchases  purchase_frequency_days
0               Fortnightly                       14
1               Fortnightly                       14
2                    Weekly                        7
3                    Weekly                        7
4                  Annually                      365
...                     ...                      ...
3895                 Weekly                        7
3896              Bi-Weekly                       14
3897              Quarterly                       90
3898                 Weekly                        7
3899              Quarterly                       90

[3900 rows x 2 columns]

In [71]:
customer[["discount_applied","promo_code_used"]]

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [73]:
(customer["discount_applied"] ==customer["promo_code_used"]).all()

np.True_

In [74]:
customer=customer.drop(columns="promo_code_used",axis = 1)

In [79]:
!pip install psycopg2-binary sqlalchemy 
from sqlalchemy import create_engine
import urllib

Requirement already satisfied: psycopg2-binary in c:\users\asus\anaconda3\lib\site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in c:\users\asus\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\asus\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\asus\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [85]:
# Step 1: Connect to SQL Server
server = "DESKTOP-1T3AL6V\SQLEXPRESS"                    #  SSMS me jo server name hai wahi likhein
database = "customer_behavior"                           #   the database you created in SSMS
driver = "ODBC Driver 18 for SQL Server"

engine = create_engine(f"mssql+pyodbc://@{server}/{database}?driver={driver.replace(' ', '+')}&trusted_connection=yes&TrustServerCertificate=yes")

table_name = "customer"
customer.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

C:\Users\Asus\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

Data successfully loaded into table 'customer' in database 'customer_behavior'.